# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
#       Stop all: docker compose down
#

version: '3.8'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-info}
  PAYMENT_PROCESSOR_URL_DEFAULT: "http://payment-processor-default:8080"
  PAYMENT_PROCESSOR_URL_FALLBACK: "http://payment-processor-fallback:8080"

services:
  nginx:
    image: nginx:alpine
    ports:
      - '9999:9999'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    restart: unless-stopped

  app1:
    image: rinha-backend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "9999"]
    restart: unless-stopped

  app2:
    image: rinha-backend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "9999"]
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
